development:
  clients:
    default:
      database: potions_api_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      database: potions_api_test
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5 